#  numpy.argwhere()

Numpy `argwhere()` function finds the indices of array elements that are nonzero, grouped by element. Python `np.argwhere()` is the same as `np.transpose(np.nonzero())`. The output of `argwhere()` function is not suitable for indexing arrays. For this purpose, use nonzero (a) instead.

Syntax : numpy.argwhere(arr)

Parameters :
arr : [array_like] Input array.

Return : [ndarray] Indices of elements that are non-zero. Indices are grouped by element.

In [22]:
import numpy as np 

In [23]:
data = [[ 11, 0, 21], [0, 19, 18]]
print(data)
nonZeroIndices = np.argwhere(data)
print(nonZeroIndices)

[[11, 0, 21], [0, 19, 18]]
[[0 0]
 [0 2]
 [1 1]
 [1 2]]


In the above code 11 is not zero and its index is [0, 0] means on 0 row and 0 column 11 element is there. So it returns [0 ,0]. Same for 21 element whose index is [0, 2].

Same for 19 whose index is [1, 1] because not row is 1, and in that row, the column is also 1. That is why it returns [1, 1] and the same for 18 whose index is [1, 2].

In [24]:
# input array 
in_arr = [[ 2, 0, 7], [ 0, 5, 9]] 
print ("Input array : ", in_arr)  

Input array :  [[2, 0, 7], [0, 5, 9]]


In [25]:
out_arr = np.argwhere(in_arr) 
print ("Output indices of non zero array element: \n", out_arr) 

Output indices of non zero array element: 
 [[0 0]
 [0 2]
 [1 1]
 [1 2]]


in the first row: [0,0] and [0,2] are non-zero
in the 2nd row: [1,1] and [1,2] are non-zero

In [26]:
# input array 
in_arr = np.arange(8).reshape(4, 2) 
print ("Input array : ", in_arr) 

Input array :  [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [27]:
out_arr = np.argwhere(in_arr>4) 

In [28]:
print ("Output indices greater than 4: \n", out_arr) 

Output indices greater than 4: 
 [[2 1]
 [3 0]
 [3 1]]


Can use with an argument. There are 3 elements that are bigger than 4 and their indices are [2,1], [3,0] and [3,1]

In [29]:
a = np.array([[1,2], [3,4]])
a.flatten()

array([1, 2, 3, 4])